name: Cypress Tests Poc 1

on: 
    #push

    workflow_dispatch:
    #workflow_call:
        #inputs:
            #run-name:
                #required: false
                #description: 'Test'
                #default: 'Teste completo'
                #type: string

jobs:

  calling-workflow:
      runs-on: ubuntu-22.04
      steps:
          - name: Checkout v4
            uses: actions/checkout@v4
            with:
                repository: maksonrochati/cypress-poc-2
                path: .github/workflows/qa.yml

          - name:  test
            uses: maksonrochati/cypress-poc-2/.github/workflows/qa.yml@poc2
    
   
    
    
 # cypress-run:
   # runs-on: ubuntu-22.04
   # steps:
     # - name: Checkout
      #  uses: actions/checkout@v4
       
